#=============================================================================
#=============================================================================

obj-$(CONFIG_HW_ANTENNA_BOARD_MATCH)  += antenna_board_match/
obj-$(CONFIG_ANTENNA_FPGA) += antenna_fpga/
obj-$(CONFIG_HUAWEI_AUDIO) += audio/
obj-$(CONFIG_RIL_NETLINK_MODULE)   += riltcp/
obj-$(CONFIG_RIL_SIM_NETLINK_MODULE)   += rilsim/
obj-y   += connectivity/
obj-$(CONFIG_HUAWEI_HW_DEV_DCT)  += devdetect/
obj-y   += inputhub/
obj-$(CONFIG_NFC_DEVICES)   += nfc/
obj-$(CONFIG_HW_WIFI)   += net/
obj-y   += power/
obj-$(CONFIG_HUAWEI_DSM) += recovery/
obj-$(CONFIG_HUAWEI_SENSORS_INPUT_INFO)   += sensor/
obj-y   += storage/
obj-$(CONFIG_HUAWEI_TS)   += touthscreen/
obj-y   += usb/
obj-$(CONFIG_HW_VOLTAGE_DETECTION) += voltage_detection/
obj-$(CONFIG_HUAWEI_VIBRATOR) += vibrator/
obj-$(CONFIG_MADAPT) += madapt/
obj-$(CONFIG_HUAWEI_EMCOM) += emcom/
obj-$(CONFIG_HUAWEI_VENDOR_EXCEPTION) += vendor_exception/
obj-$(CONFIG_WAKEUP) += wakeup/
