cflags-$(CONFIG_HYPERHOLD) += -I$(srctree)/mm
obj-$(CONFIG_HISI_MEM_OFFLINE) += mem_offline.o
obj-$(CONFIG_HYPERHOLD) += memcg_control.o
obj-$(CONFIG_HYPERHOLD) += memcg_reclaim.o
obj-$(CONFIG_VM_COPY) += vm_copy.o
