#=============================================================================
#  wifi
#=============================================================================
obj-$(CONFIG_HW_WIFI) += ipv4/
obj-$(CONFIG_HW_DPIMARK_MODULE) += hw_dpi_mark/
EXTRA_CFLAGS += -Idriver/huawei_platform
